"use strict";
exports.__esModule = true;
var customer_1 = require("./customer");
var Table_1 = require("./Table");
var Menu_1 = require("./Menu");
var order_1 = require("./order");
var tablearr = [];
var tab1 = new Table_1.Table(tablearr.length + 1, 4, 2, "table1");
tablearr.push(tab1);
var tab2 = new Table_1.Table(tablearr.length + 1, 7, 5, "table2");
tablearr.push(tab2);
var tab3 = new Table_1.Table(tablearr.length + 1, 2, 3, "table3");
tablearr.push(tab3);
var tab4 = new Table_1.Table(tablearr.length + 1, 6, 3, "table4");
tablearr.push(tab4);
console.log(tablearr);
var custarr = [];
var cust1 = new customer_1.Customer(custarr.length + 1, "parag", "rajkot", 22, "abc heights", 4561237890);
custarr.push(cust1);
var cust2 = new customer_1.Customer(custarr.length + 1, "brijen", "ahemdabad", 19, "xyz heights", 8529631420);
custarr.push(cust2);
var cust3 = new customer_1.Customer(custarr.length + 1, "jeel", "jetpur", 21, "opq heights", 3212548969);
custarr.push(cust3);
console.log(custarr);
// table booking
var todate = new Date();
tab1.bookForNextHour(cust1, todate);
console.log(tab1);
tab2.bookForNextMonth(cust1, todate);
var menuarr = [];
var menu1 = new Menu_1.Menu(menuarr.length + 1, "Punjabi dish", 4, "Punjabi", 250);
menuarr.push(menu1);
var menu2 = new Menu_1.Menu(menuarr.length + 1, "dhosa ", 3, "south indian", 192);
menuarr.push(menu2);
var menu3 = new Menu_1.Menu(menuarr.length + 1, "gujrati dish", 6, "normal", 120);
menuarr.push(menu3);
console.log(menuarr);
var order = new order_1.Order();
var menuqtyarr = [[menu1, 4], [menu2, 2]];
order.orederMenu(menuqtyarr, cust1, new Date());
